services:
  back:
    build: ./back
    ports:
      - "8005:80"
    volumes:
      - back_data:/var/www/html/var
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
      # On force l'URL SQLite vers le dossier var/
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data.db"

  # Frontend Vue
  front:
    build: ./front
    ports:
      - "8085:80"
    depends_on:
      - back

volumes:
  back_data:
