services:
  back:
    build: ./back
    image: ghcr.io/mattisbbn/cours-vue/back:latest
    ports:
      - "8005:80"
    volumes:
      - back_data:/app/var
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
      SERVER_NAME: ":80"
      DATABASE_URL: "sqlite:///%kernel.project_dir%/var/data.db"
  front:
    build: ./front
    image: ghcr.io/mattisbbn/cours-vue/front:latest
    ports:
      - "8085:80"
    depends_on:
      - back

volumes:
  back_data:
